pryt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
]

root/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import CreateRoom, UpdateRoom, DeleteRoom, LoginView, SignUpView, RoomView, DeleteMessage

app_name = "root"
urlpatterns = [
    path('', views.main_page, name="main-page"),

    # Rooms
    path('room/<int:pk>/', RoomView.as_view(), name="room"),
    path('create-room/', login_required(CreateRoom.as_view(), login_url='root:login'), name="create-room"),
    path('update-room/<int:pk>', login_required(UpdateRoom.as_view(), login_url='root:login'), name="update-room"),
    path('delete-room/<int:pk>', login_required(DeleteRoom.as_view(), login_url='root:login'), name="delete-room"),

    # User authentication
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),

    # Messages
    path('delete-message/<int:pk>', login_required(DeleteMessage.as_view()), name='delete-message'),

    # User profile
    path('profile/<int:pk>', views.user_profile, name="user-profile")
]

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pryt</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <link href="{% static 'styles/main.css' %}" rel="stylesheet" type="text/css">
    {% bootstrap_javascript %}
</head>
<body>
{% include 'navbar.html' %}

{% block content %}
{% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}
<header class="container-fluid mt-4">
    <section class="d-flex bd-highlight mb-3 align-items-center">
        <section class="p-2 bd-highligh">
            <h1 class="h1"><a class="no-style" href="{% url 'root:main-page' %}">Pryt</a></h1>
        </section>

        <section class="p-2 bd-highligh">
            <form method="get" action="{% url 'root:main-page' %}">
                <input class="form-control border-secondary rounded-pill " type="text" name="q" placeholder="Search...">
            </form>
        </section>

        <section class="ms-auto p-2 bd-highlight text-center">
            {% if request.user.is_authenticated %}
                <img class=".img-thumbnail" src="{% static 'img/avatar.png' %}" alt="user profile image" width="40">
                <p><a class="profile-username-p" href="{% url 'root:user-profile' request.user.id %}">{{ request.user.first_name }} {{ request.user.last_name }} | @{{ request.user }}</a></p>
                <a href="{% url 'root:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'root:login' %}">Login</a>
            {% endif %}
        </section>
    </section>
</header>