pryt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
]

root/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from .views import CreateRoom, UpdateRoom, DeleteRoom, LoginView, SignUpView, RoomView, DeleteMessage

app_name = "root"
urlpatterns = [
    path('', views.main_page, name="main-page"),

    # Rooms
    path('room/<int:pk>/', RoomView.as_view(), name="room"),
    path('create-room/', login_required(CreateRoom.as_view(), login_url='root:login'), name="create-room"),
    path('update-room/<int:pk>', login_required(UpdateRoom.as_view(), login_url='root:login'), name="update-room"),
    path('delete-room/<int:pk>', login_required(DeleteRoom.as_view(), login_url='root:login'), name="delete-room"),

    # User authentication
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),

    # Messages
    path('delete-message/<int:pk>', login_required(DeleteMessage.as_view()), name='delete-message'),

    # User profile
    path('profile/<int:pk>', views.user_profile, name="user-profile")
]

root/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    name = models.CharField(max_length=170)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:20]

root/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Room
from django import forms


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['topic', 'name', 'description']


class LoginForm(forms.Form):
    username = forms.CharField(label="Username",
                               widget=forms.TextInput(
                                   attrs={
                                       'placeholder': 'Enter your username...',
                                       # 'class': 'form-control border-secondary rounded-pill'
                                   }
                               )
                               )
    password = forms.CharField(label="Password",
                               widget=forms.TextInput(
                                   attrs={
                                       'placeholder': 'Enter your password...',
                                       'type': 'password',
                                       #'class': 'form-control border-secondary rounded-pill'
                                   }
                               )
                               )


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )

root/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect

from .models import Room, Topic, Message
from django.views import View
from .forms import RoomForm, LoginForm, UserRegisterForm


def main_page(request):
    query = request.GET.get('q') if request.GET.get('q') is not None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=query) |
        Q(name__icontains=query) |
        Q(description=query)
    )
    topics = Topic.objects.all()
    context = {'rooms': rooms, 'topics': topics}

    return render(request, 'root/main_page.html', context)


class RoomView(View):
    def dispatch(self, request, *args, **kwargs):
        self.room = Room.objects.get(id=kwargs['pk'])
        self.messages = self.room.message_set.all().order_by('created')
        self.participants = self.room.participants.all()
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        context = {
            'room': self.room,
            'messages': self.messages,
            'participants': self.participants
        }
        return render(request, 'root/room.html', context)

    def post(self, request, pk):
        Message.objects.create(
            user=request.user,
            room=self.room,
            body=request.POST.get('body')
        )
        self.room.participants.add(request.user)
        return redirect('root:room', pk=self.room.id)


class CreateRoom(View):
    def dispatch(self, request, *args, **kwargs):
        self.form = RoomForm(request.POST or None)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {'form': self.form}
        return render(request, 'root/room_form.html', context)

    def post(self, request):
        if self.form.is_valid():
            room = self.form.save(commit=False)
            room.host = request.user
            room.save()
            return redirect('root:main-page')


class UpdateRoom(View):
    def dispatch(self, request, *args, **kwargs):
        self.room = Room.objects.get(id=kwargs['pk'])
        if request.user != self.room.host:
            return render(request, 'root/user_error.html', {'message': 'You are not allowed to access this page'})
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        form = RoomForm(instance=self.room)
        context = {'form': form}
        return render(request, 'root/room_form.html', context)

    def post(self, request, pk):
        form = RoomForm(request.POST, instance=self.room)
        if form.is_valid():
            form.save()
            return redirect('root:main-page')


class DeleteRoom(View):
    def dispatch(self, request, *args, **kwargs):
        self.room = Room.objects.get(id=kwargs['pk'])
        if request.user != self.room.host:
            return render(request, 'root/user_error.html', {'message': 'You are not allowed to access this page'})
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        context = {'element': self.room}
        return render(request, 'root/delete.html', context)

    def post(self, request, pk):
        self.room.delete()
        return redirect('root:main-page')


class LoginView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('root:main-page')

        self.form = LoginForm(request.POST or None)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {'form': self.form}
        return render(request, 'root/login.html', context)

    def post(self, request):
        if self.form.is_valid():
            username = self.form.cleaned_data['username'].lower()
            password = self.form.cleaned_data['password']

            try:
                User.objects.get(username=username)
            except User.DoesNotExist:
                return render(self.request, 'root/user_error.html', {'message': 'User not found'})

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('root:main-page')
            else:
                return render(self.request, 'root/user_error.html', {'message': 'Invalid credentials'})


def logout_user(request):
    logout(request)
    return redirect('root:main-page')


class SignUpView(View):
    def dispatch(self, request, *args, **kwargs):
        self.form = UserRegisterForm(request.POST or None)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {'form': self.form}
        return render(request, 'root/sign_up.html', context)

    def post(self, request):
        if self.form.is_valid():
            user = self.form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            return redirect('root:login')
        else:
            return render(self.request, 'root/user_error.html', {'message': 'Invalid credentials: passwords do not '
                                                                            'match'})


class DeleteMessage(View):
    def dispatch(self, request, *args, **kwargs):
        self.message = Message.objects.get(id=kwargs['pk'])
        self.room = Room.objects.get(id=request.GET.get('pk2'))
        if request.user != self.message.user:
            return render(request, 'root/user_error.html', {'message': 'You are not allowed to access this page'})
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        context = {'element': self.message}
        return render(request, 'root/delete.html', context)

    def post(self, request, pk):
        self.message.delete()

        user_messages = Message.objects.filter(room=self.room, user=request.user)

        if not user_messages.exists():
            # If the user has no messages, remove them from the room participants
            self.room.participants.remove(request.user)

        return redirect('root:room', pk=self.room.id)


def user_profile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    messages = user.message_set.all()
    topics = Topic.objects.all()
    room_count = rooms.count()
    context = {
        'user': user,
        'rooms': rooms,
        'messages': messages,
        'topics': topics,
        'room_cout': room_count
    }
    return render(request, 'root/profile.html', context)

root/templates/root/delete.html
{% extends 'main.html' %}

{% block content %}
    <section class="container">
        <form method="post" action="">
            {% csrf_token %}
            <h3 class="h3">Do you want to delete {{ element }}?</h3>
            <p><a href="{{ request.META.HTTP_REFERER }}">Go to previous page</a></p>
            <input class="btn" type="submit" value="Delete" />
        </form>
    </section>
{% endblock %}

root/templates/root/login.html
{% extends 'main.html' %}
{% load crispy_forms_filters %}

{% load crispy_forms_tags %}
 {% block content %}

     <section class="container text-start">
        <form method="post" action="" >
            {% csrf_token %}
            {{ form|crispy }}

            <input class="btn" type="submit" value="Login">
        </form>
        <div class="mt-4">
            <a href="{% url 'root:sign-up' %}">Don't have an account? Create your account here</a>
        </div>
     </section>


 {% endblock %}

root/templates/root/main_page.html
{% extends 'main.html' %}

{%  block content %}

{% comment %}<style>
    .main-ct {
        display: grid;
        grid-template-columns: 1fr 3fr;
    }
</style>{% endcomment %}

<main class="container text-center mt-4">
    <section class="row">
        <aside class="col-2">
            {% include 'root/main_components/topics_component.html' %}
        </aside>

        <section class="col-8">
            {% include 'root/main_components/room_component.html' %}
        </section>

    </section>
</main>
{% endblock %}
</body>
</html>

root/templates/root/profile.html
{% extends 'main.html' %}

{% block content %}
{% comment %}    <style>
        .profile {
            display: grid;
            grid-template-columns: 1fr 2fr 1fr;
        }
    </style>{% endcomment %}

    <header class="container mt-3">
       <h1 class="h1 text-center">{{ user.first_name }} {{ user.last_name }}</h1>
    </header>
    <main class="container text-center mt-5">
        <section class="row">

            <aside class="col">
                {% include 'root/main_components/topics_component.html' %}
            </aside>

            <section class="col-6">
                <p>Host of {{ room_cout }} room/s</p>
                {% include 'root/main_components/room_component.html' %}
            </section>

            <section class="col">
                <h3 class="h3">Recent activity </h3>
                <hr>
                {% for message in messages %}
                    <article class="mb-2">
                        <span>@{{ message.user }} {{ message.created|timesince }} ago</span>
                        <small>Replied to room "{{ message.room }}"</small>
                        <p>{{ message.body }}</p>
                    </article>
                {% endfor %}
            </section>
        </section>
    </main>


{% endblock %}

root/templates/root/room.html
{% extends 'main.html' %}

{%  block content %}
    {% comment %}<style>
        .room {
            display: grid;
            grid-template-columns: 3fr 1fr;
        }
    </style>{% endcomment %}

    <header class="container mt-4 mb-3">
        <h1 class="h1">{{ room.name }}</h1>
        <p class="lead">{{ room.description }}</p>
    </header>
    <main class="container text-center">
        <section class="row">
            <section class="col-8">
                <h2 class="h2 text-start mb-3">Chat</h2>
                <section class="scroll">
                    {% for message in messages %}
                        <article class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex bd-highlight mb-3">
                                    <div class="me-auto p-2 bd-highlight">
                                        <p>{{ message.body }}</p>
                                    </div>
                                    <div class="p-2 bd-highlight">
                                        <span class="badge rounded-pill-badge rounded-pill"><span class="rounded-pill-badge-user">@{{ message.user }}</span> - {{ message.created|timesince }} ago</span>
                                        {% if request.user == message.user %}
                                        <a href="{% url 'root:delete-message' message.id %}?pk2={{ room.id }}">Delete</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                </section>

                {% if request.user.is_authenticated %}
                <section class="room-chat-form">
                    <form method="post" action="">
                        {% csrf_token %}
                        <input  class="form-control border-secondary rounded-pill " type="text" name="body" placeholder="Write a message..." />
                    </form>
                </section>
                {% endif %}
            </section>

            <aside class="col-4">
                <h2>Participants</h2>
                <hr>
                {% for p in participants %}
                    <article>
                        <a href="{% url 'root:user-profile' p.id %}">@{{ p.username }}</a>
                    </article>
                {% endfor %}
            </aside>
        </section>
    </main>
{% endblock %}

root/templates/root/room_form.html
{% extends 'main.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <section class="container text-start">
        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn" type="submit" value="Submit" />
        </form>
    </section>
{% endblock content %}

root/templates/root/sign_up.html
{% extends 'main.html' %}
{% load crispy_forms_filters %}

{% block content %}

     <section class="container text-start">
        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn" type="submit" value="Sign Up">
        </form>
         <div class="mt-4">
             <a href="{% url 'root:login' %}">Already have an account? Login here</a>
         </div>
     </section>

 {% endblock %}

root/templates/root/user_error.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pryt</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <link href="{% static 'styles/main.css' %}" rel="stylesheet" type="text/css">
    {% bootstrap_javascript %}
</head>
<body class="container mt-4">

    <h2 class="h2">{{ message }}</h2>
    <p><a href="{% url 'root:main-page' %}">Go to main page</a></p>

</body>